language: node_js

node_js:
  - "11.10.1"

install:
  - npm install

script:
  - npm run test -- --coverage && npm run test:automation:run

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
